version: "3"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      env_file:
        - database.env
      volumes:
        - database-data:/var/lib/postgresql/DiscountJira/data/ # persist data even if container shuts down

volumes:
  database-data:
